AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ImageGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: image_generator_49_v2.app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Role: !GetAtt ImageGenerationFunctionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers"
          CANDIDATE_NUMBER: "49"
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

  ImageGenerationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ImageGenerationPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-image-generator-v1
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: arn:aws:s3:::pgr301-couch-explorers/49/generated_images/*
